### ISSUE TITLE
https://dgmcdona.github.io/2021/09/11/CSAW-CTF-2021-ransomewaRE-Writeup.html

### ISSUE THREAD

**Issue by evandrix** [dgmcdona/dgmcdona.github.io#1]
any chance you could share the encryptor.exe i.e. http://rev.chal.csaw.io:8129/5692481aecd40429eecf588d28ce6a31 pls?
http://rev.chal.csaw.io:8129 is down, now that the CTF is over

**Comment by dgmcdona** [comment]
No problem, just added a hyperlink to the download right above the first part of the script.
